# -*- coding: utf-8 -*-
"""Assignment2_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OcOX6JhLshzM4RcULFH2jYSCLyHcWV5
"""

def Numerology_Number_Calculation():
  sum1,sum=0,0
  full_name=input("Enter the Name: ")
  Date_of_birth=input("Enter DOB For Numerology Calculation: ")
  Date_of_birth=Date_of_birth.replace(" ","")
  if len(Date_of_birth) > 11:
    print("Enter valid information")
    Numerology_Number_Calculation()
  else:
    for char in Date_of_birth:
      if (char.isdigit()==1):
        sum+=int(char)
    numberology={ 1: { "positive": "Natural leader, confident, ambitious, independent thinker.", "negative": "Can be egoistic, impatient, dominating." }, 2: { "positive": "Diplomatic, cooperative, emotional intelligence strong.", "negative": "Over-sensitive, dependent, indecisive." }, 3: { "positive": "Creative, expressive, social, optimistic.", "negative": "Scattered focus, dramatic, inconsistent." }, 4: { "positive": "Practical, disciplined, hardworking, loyal.", "negative": "Rigid, stubborn, resistant to change." }, 5: { "positive": "Adventurous, energetic, loves freedom, adaptable.", "negative": "Restless, impulsive, lacks consistency." }, 6: { "positive": "Responsible, caring, family-oriented, balanced.", "negative": "Overprotective, controlling, self-sacrificing." }, 7: { "positive": "Analytical, spiritual, intelligent, deep thinker.", "negative": "Overthinking, isolated, emotionally distant." }, 8: { "positive": "Ambitious, business-minded, powerful personality.", "negative": "Materialistic, workaholic, aggressive." }, 9: { "positive": "Compassionate, humanitarian, generous, wise.", "negative": "Emotionally intense, moody, unrealistic." } }


  if sum>9:
    while sum>0:
      rem=sum%10
      sum1=sum1+rem
      sum=sum//10
  print(f"---------------------------------- Hello {full_name} Your Numerology Number is: {sum1}\n ----------Positive Traits------------------------ ✨\n {numberology[sum1]["positive"]}--Negative Traits ⚠ {numberology[sum1]["negative"]}")

while True:
  print("-----------------------------------------------------")
  print("--------------Numerology personality App-------------")
  print("--------------1 Numerology Number Calculation--------")
  print("--------------0 Exit  for loop-----------------------")
  print("-----------------------------------------------------")
  choice=(input("Enter your choice:  "))
  if choice=='1':
    Numerology_Number_Calculation()
  elif choice=='0':
    print("Thankyou for using Numerology Number Calculation")
    break
  else:
    print("Invalid choice please choose again")