# -*- coding: utf-8 -*-
"""Assignment1_amarpanchalsir_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BijRxq0q-01Y_w573iRpkJoVIYhbx7S6
"""

def menu():
  print("==============================")
  print("---SHOP INVENTORY MANAGER-----")
  print("==============================")
  print("-----1. Add New Product-------")
  print("-----2. Sell Product----------")
  print("-----3. Restock Product-------")
  print("-----4. View Stock Report-----")
  print("-----5. Exit------------------")
  print("------------------------------")


def Add_New_Product(product,price,quantity):

  product_name=input("enter you product name: ")
  price_per_unit=float(input("enter the price per unit charges: "))
  quantity_of_item=int(input("enter the quantity of the product: "))

  if product_name in product:
    print(f"{product_name} already exists in inventory!")
  else:
    product.append(product_name)
    price.append(price_per_unit)
    quantity.append(quantity_of_item)
    print(f"{product_name} added successfully!")
  return product,price,quantity

def Sell_Product(product,price,quantity):
  sell_product=input("enter product name")
  quantity_to_sell=int(input("enter quantity to sell"))
  index=product.index(sell_product)
  if sell_product not in product:
    print(f"{sell_product} not found in inventory!")

  elif quantity_to_sell> quantity[index]:
    print(f"Not enough stock! Only {quantity[index]} units available.")
  else:

     quantity[index]=quantity[index]-quantity_to_sell
     print(f" Sold {quantity_to_sell} \n units of Apple Sale Value :{price[index]*quantity_to_sell}\n Remaining Stock: {quantity[index]}\n units")

def Restock_product(product,price,quantity):
  restock_product=input("Enter product name :")
  quantity_to_restock=int(input("Enter quantity to add :"))
  if restock_product in product:
    index=product.index(restock_product)
    quantity[index]=quantity[index]+quantity_to_restock
    print(f"Mango restocked! New quantity: {quantity[index]} units")
  else:
    print("product not found")


def View_Stock_Report(product,price,quantity):
    total=0
    print("====================================================")
    print("        📦 STOCK REPORT                             ")
    print("====================================================")
    print("No.  Product     Price    Qty     Status")
    print("----------------------------------------------------")
    for i in range(len(product)):
       if quantity[i]>=5:
           print(f"{i+1}.   {product[i]}       ₹{price[i]}        ✅ Available")
       elif 0<quantity[i]<5:
           print(f"{i+1}.   {product[i]}       ₹{price[i]}       ⚠️  LOW STOCK")
       elif quantity[i]==0:
          print(f"{i+1}.   {product[i]}       ₹{price[i]}        ❌ OUT OF STOCK")
       total+=price[i]*quantity[i]
    print("----------------------------------------------------")
    print(f"Total Products        : {len(product)}")
    print(f"Total Inventory Value : ₹{total}")
    print("====================================================")


product=[]
price=[]
quantity=[]


while True:
  menu()
  choice=int(input('enter your choice :-'))
  if choice==1:
     Add_New_Product(product,price,quantity)
  elif choice==2:
    Sell_Product(product,price,quantity)
  elif choice==3:
    Restock_product(product,price,quantity)
  elif choice==4:
    View_Stock_Report(product,price,quantity)
  elif choice==5:
    break
  else:
    print("invalid choice please re-enter")

